//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Images
    {
        public int Id { get; set; }
        public int Product_Id { get; set; }
        public Nullable<System.DateTime> Addition_Date { get; set; }
        public Nullable<bool> IsMain_Img { get; set; }
        public string Image_Path { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
